export const theme = {
  bg: '#1a0a0f',
  card: '#2a1520',
  white: '#f7f7f7',
  text: 'white',
  sub: 'rgba(255,255,255,0.6)',
  border: 'rgba(255,255,255,0.1)',
  orange: '#ff6b00',
  green: '#27ae60',
};

export const commonStyles = {
  container: {
    maxWidth: '480px',
    margin: '0 auto',
    minHeight: '100vh',
    background: '#1a0a0f',
    paddingBottom: '70px',
    color: 'white',
  },
  header: {
    background: '#ff6b00',
    padding: '50px 16px 15px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    color: 'white',
  },
  backBtn: {
    background: 'rgba(255,255,255,0.2)',
    border: 'none',
    color: 'white',
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    fontSize: '22px',
    cursor: 'pointer',
  },
  headerTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: 'white',
    flex: 1,
  },
  card: {
    background: '#2a1520',
    borderRadius: '16px',
    padding: '16px',
    marginBottom: '12px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
  },
  input: {
    width: '100%',
    padding: '13px 15px',
    border: '1.5px solid rgba(255,255,255,0.15)',
    borderRadius: '12px',
    fontSize: '15px',
    outline: 'none',
    boxSizing: 'border-box',
    background: '#2a1520',
    color: 'white',
    marginBottom: '12px',
  },
  btn: {
    width: '100%',
    padding: '15px',
    background: '#ff6b00',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    fontSize: '16px',
    fontWeight: '700',
    cursor: 'pointer',
    marginTop: '10px',
    boxSizing: 'border-box',
  },
  bottomNav: {
    position: 'fixed',
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '100%',
    maxWidth: '480px',
    background: '#1a0a0f',
    borderTop: '1px solid rgba(255,255,255,0.1)',
    display: 'flex',
    zIndex: 100,
    boxShadow: '0 -2px 10px rgba(0,0,0,0.3)',
  },
  navItem: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '3px',
    padding: '10px 5px',
    cursor: 'pointer',
    color: 'rgba(255,255,255,0.5)',
    fontSize: '11px',
  },
  navIcon: { fontSize: '22px' },
};
